# Generated by Django 5.2.4 on 2025-08-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bike_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='car_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
