# Generated by Django 5.2.4 on 2025-08-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_alter_customuser_bike_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bike_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='car_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
