# Generated by Django 5.2.4 on 2025-08-08 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_alter_customuser_bike_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_approvals', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(db_column='flat', on_delete=django.db.models.deletion.CASCADE, related_name='flat_num_reqest', to=settings.AUTH_USER_MODEL)),
                ('purpose', models.ForeignKey(limit_choices_to={'type__code': 'visitor_purpose'}, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_purpose', to='society.mastervalue')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatekeeper_requests', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(limit_choices_to={'type__code': 'status'}, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_req_status', to='society.mastervalue')),
            ],
        ),
    ]
