# Generated by Django 5.2.4 on 2025-08-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0006_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='society_role',
            field=models.CharField(blank=True, choices=[('president', 'president'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary')], max_length=30, null=True),
        ),
    ]
