# Generated by Django 5.2.4 on 2025-08-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0007_profileimage_society_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='society_role',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary')], max_length=30, null=True),
        ),
    ]
